### ISSUE TITLE
Update to new Theme Settings

### ISSUE THREAD

**Issue by fpaguiar** [rose-pine/slack#3]
The new theme settings unfortunately got a lot more restricted, but just wondering if there's any plan to adjust the theme to it.

<img width="532" alt="image" src="https://github.com/rose-pine/slack/assets/22917135/6dedca45-f198-4638-b746-7f116e21b533">

**Comment by fpaguiar** [comment]
Nvm, I just saw you can import legacy themes.

**Comment by mvllow** [comment]
We'll probably get around to adding the new format—there's not many theming options so it's probably best to simply copy values from https://rosepinetheme.com/palette for a more personalised experience. Glad you were able to get the legacy imported :)
